### ISSUE TITLE
404-to-301 plugin prevents correct plugin enumeration

### ISSUE THREAD

**Issue by Xenopathic** [wpscanteam/wpscan#1061]
With the 404-to-301 plugin enabled (tested with 2.2.8 installed, vulnerable to the XSS fixed in 2.3.1) and the redirect set to a custom URL with target `/`, wpscan will not detect the plugin. Changing the target to a different string, e.g. the full URL `http://mysite.com`, or turning off the redirection, allows wpscan to again detect the plugin.

Tested with wpscan 2.9.2, Wordpress 4.7.2 and 404-to-301 2.2.8.

**Comment by ethicalhack3r** [comment]
Thanks for the report!

Do you have the same issue with WPScan v3 BETA? https://github.com/wpscanteam/wpscan-v3

**Comment by Xenopathic** [comment]
Yes, I can reproduce the issue with WPScan v3 (commit dd9ea8b1d5b416d9578cfd941b79e5d4d6f2367f for completeness)

**Comment by erwanlr** [comment]
Was able to reproduce but this is extremely weird.

First of all, if you set the Custom URL to '/' in the 404-to-301 settings, it's a misconfiguration. You should not be able to do that, as all 404 will be redirected to http:/// apparently

Now the weird part, if I proxy wpscan's requests through burp, the plugin is detected. If not, it's not detected. Not ideal to debug :/

**Comment by erwanlr** [comment]
Due to the 404-to-301 being misconfigured, all 404 page's bodies are empty basically.
This causes the 404_hash (md5sum of a 404's body) used by WPScan to equal a 200 with an empty body, and as a result, during the plugin enumeration plugins are not detected as their response's body == a 404.

Now, using Burp, plugins were detected because burp issued errors caused by the invalid Location header 'http:///' resulting in the 404_hash being different than a 200 with an empty body.

Not much we can do in such case

**Comment by Xenopathic** [comment]
Now that's a strange bug! Browsers seem to accept the malformed redirect though, and the 404-to-301 plugin does not complain when setting that redirect URL, so perhaps wpscan should do its best to detect this case anyway despite it being out-of-spec?
