### ISSUE TITLE
Error wpscan

### ISSUE THREAD

**Issue by 3jgvc** [wpscanteam/wpscan#1139]
Hello

wpscan does not detect wordpress. It displays the error "[!] The remote website is up, but does not seem to be running WordPress."

**Comment by ethicalhack3r** [comment]
We'll is it?

**Comment by 3jgvc** [comment]
I did : ruby wpscan.rb --url mywebsite.com and ruby wpscan.rb --url mywebsite.com --force
and I have the following result : [!] The remote website is up, but does not seem to be running WordPress.

**Comment by 3jgvc** [comment]
Up

**Comment by erwanlr** [comment]
That's weird, using the --force, you can't have such error ;p

@ethicalhack3r asked you whether or not you are sure the site you are scanning is running WP though, which might be the issue here. However, as you wrote 'mywebsite.com' as example in your command, I guess it's yours and you know it's WP (unless typo in the real url for example)

If you are sure the targeted site is running WP, then please try with the v3 or send us the URL: team at wpscan dot org

**Comment by 3jgvc** [comment]
Sorry for misunderstanding. I sent the email containing the link! : p

**Comment by erwanlr** [comment]
There is a protection mechanism requiring a cookie with a specific value to be sent along the requests. To get it, open the site in a browser and get the related cookie, then supply it to WPScan, example:

v2: ```./wpscan.rb --cookie '__test=c0b6c2b606d92a6a828b4f834f7fd809' --url http://target.tld```
v3: ```wpscan --cookie-string '__test=c0b6c2b606d92a6a828b4f834f7fd809' --url http://target.tld```

**Comment by 3jgvc** [comment]
Problem solved! Thank you for your help.
