### ISSUE TITLE
Versions of WPML and sitepress-multilingual-cms could not be determined

### ISSUE THREAD

**Issue by ac0v** [wpscanteam/wpscan#1157]
Hi,

I've the following issues running a scan on a fully- updated WP site - would it be possible to specify some versions when calling wpscan, or providing wpscan with some credentials to determine the installed versions (I know, that the later is not safe).:

```
[!] We could not determine a version so all vulnerabilities are printed out

[!] Title: sitepress-multilingual-cms - Full Path Disclosure
    Reference: https://wpvulndb.com/vulnerabilities/6104
[i] Fixed in: 3.1.7.2

[!] Title: WPML <= 3.1.7.2 - Multiple Vulnerabilities (Including SQLi)
    Reference: https://wpvulndb.com/vulnerabilities/7843
    Reference: http://seclists.org/bugtraq/2015/Mar/60
    Reference: http://wpml.org/2015/03/wpml-security-update-bug-and-fix/
    Reference: http://packetstormsecurity.com/files/130810/
    Reference: http://klikki.fi/adv/wpml.html
    Reference: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-2314
    Reference: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-2791
    Reference: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-2792
    Reference: https://www.exploit-db.com/exploits/36414/
[i] Fixed in: 3.1.9

[!] Title: WPML 2.9.3-3.2.6 - Cross-Site Scripting (XSS) in Accept-Language Header
    Reference: https://wpvulndb.com/vulnerabilities/8173
    Reference: http://blog.secupress.fr/en/xss-wpml-header-405.html
[i] Fixed in: 3.2.7
```

Cheers,
ac0v

**Comment by ethicalhack3r** [comment]
@erwanlr, @_FireFart_ what do you think of using a flag to not output all the data when a version is not found? or, only showing all the the data when verbose flag is given?

**Comment by erwanlr** [comment]
No.

Here there two issues.

First, it seems that credentials to access the admin panel of the blog can be obtained, so using wpscan is not a good choice. Instead, plugins using the WP Vuln DB should be used and will produce better results. I think there is even a CLI tool which can connect to the WP API of the blog and check stuff. Maybe those could be added to the Readme here.

Then, when a version can't be found, suppressing output is the wrong way to go. Instead, better detection should be done, and the v3 is already way better at that (e.g., the sitepress-multilingual-cms version has 3 new ways for being detected - in the master branch, so use docker / build from source to try it), and with the fact that version detection can be added on the fly by us, users will just need to update the DB to benefit them, that's xMas time ;D

I don't like the whole stuff being output either when the version can't be found, but I prefer that rather than having to re-scan using a flag. Instead, I check the target/related plugin and add a new finder to accurately detect the version - Like I have been doing int the past two weeks in the 3.1.0 branch ^^

**Comment by erwanlr** [comment]
Handled in the v3 since the 3.1.0
