### ISSUE TITLE
Not finding wordpress site even though it does exist

### ISSUE THREAD

**Issue by ModernAesthetics** [wpscanteam/wpscan#1176]
I have tried --force and then it wants me to provide wp_content_dir which I do and then it says target seems to be down even though it is clearly up.

Using Version 2.9.4-dev
Ruby 2.5 on Windows

**Comment by ethicalhack3r** [comment]
I think the two most likely scenarios are:

1. The application is actively blocking some requests due to a security plugin or WAF. In this case try ```--random-agent```. If that doesn't work, proxy WPScan's traffic through a proxy (Burp, ZAP) and see which requests are causing the site to block, and then try to avoid those specific requests, or find a bypass.

2. The site can't handle the amount of requests in a short space of time. In this case try lowing the threads with the ```--threads``` option, or try to throttle requests with the ```--throttle``` option.

**Comment by ModernAesthetics** [comment]
The interesting thing is when I run wpscan using my kali vm it works just fine on the same sites

**Comment by AgoraSecurity** [comment]
Y think some network analysis could help understand what´s happening.
Either via a proxy or though a network capture (using tcpdump, wireshark, etc.).

I´m thinking that the server may be blocking the connections or wpscan may "get stuck" somewhere, anyhow some output from the console (debug mode enabled) and a pcap file could help understand better what´s going on...

**Comment by erwanlr** [comment]
Feel free to open a new issue if you still have the issue with the v3
