### ISSUE TITLE
nonexistent vulnerable themes detected

### ISSUE THREAD

**Issue by Bangker** [wpscanteam/wpscan#1248]
### Subject of the issue
This is similar to the issue I saw in 2.x where plugins were reported as vulnerable that did not exist on the sites.

Scans of some of my sites producing large number of vulnerable themes (355 at last scan)
I scan several websites weekly with WPScan.  Lately, about 10% of them have been returning 355 vulnerable themes. The rest seem to be detecting the themes properly, more in line with the old 2.x versions were showing.  The sites returning this data are across 7 different web servers.

### Your environment
* Version of WPScan: 3.4.0
* Version of Ruby:?
* Operating System (OS):Kali 

### Steps to reproduce
Normally, I run this command, changing the url for each site:
docker run -it --rm wpscanteam/wpscan --rua --wp-version-all -e vp,vt,u1-100 -f json --no-update --url site.com | tee site.com.txt

### Expected behavior
Expect to see an accurate listing of vulnerable themes

### Actual behavior
for about 10% of sites, 355 vulnerable themes are reported

### What have you already tried
I have tried using --themes-detection and --themes-version-detection with passive and aggressive.  With passive, no vulnerable themes are reported, with anything else, 355.  I've tried using aggressive with other sites that had reported zero vulnerable themes, and they still report zero.

Any suggestions?
Thanks.

**Comment by erwanlr** [comment]
Likely due to the responses being 200/30x instead of 404, can happen when there is a plugin (such as SEO) redirecting 404 with specific keywords in the URL to other pages.

Use the ```--exclude-content-based``` option to filter them. However, you will have to determine a keyword (either in the body or headers) in those pages. For example, if all the false positive pages contain the word 'aaa', you will have to supply ```--exclude-content-based aaa``
