### ISSUE TITLE
to_s in JSON output

### ISSUE THREAD

**Issue by FireFart** [wpscanteam/wpscan#1269]
@erwanlr is the `to_s` entry in the JSON output needed? Looks like smth. we forgot to remove (it's the same as the URL)

![image](https://user-images.githubusercontent.com/105281/50853898-e3807180-1383-11e9-8a7c-f01055eb17b4.png)

**Comment by erwanlr** [comment]
Yes, it's needed. It's used as a title (instead of the :url) in some cases

**Comment by FireFart** [comment]
So would it make sense to merge these two fields into a single one? Do you have an example of an interesting finding with different content on url and to_s?

**Comment by erwanlr** [comment]
Can't merge them, otherwise I would have done it.

Example of this being used:
- https://github.com/wpscanteam/wpscan/blob/master/app/finders/interesting_findings/multisite.rb#L22
- https://github.com/wpscanteam/wpscan/blob/master/app/finders/interesting_findings/mu_plugins.rb#L19
- https://github.com/wpscanteam/wpscan/blob/master/app/finders/interesting_findings/registration.rb#L25

What's the issue with having the to_s in the JSON ?

**Comment by FireFart** [comment]
It just looked like unneeded information but this cleared it up thanks :)
