### ISSUE TITLE
Extracting all users using WP-JSON and pagination

### ISSUE THREAD

**Issue by melalj** [wpscanteam/wpscan#1285]
### Subject of the issue
Maybe it's more a feature request than an issue.
When WPScan pulls users if wp-json is detected, it gets only the default 10 users: 
https://github.com/wpscanteam/wpscan/blob/d268a86795f178fa60f0f9f1e53a3fd08de860ba/app/finders/users/wp_json_api.rb#L30

While there may be much more users available, for example:
https://wp.lab/wp-json/wp/v2/tags/?per_page=100&page=1
https://wp.lab/wp-json/wp/v2/tags/?per_page=100&page=2
...

Let me know if that makes sense, I can pull a request to add pagination 😉 

### Your environment
* used the latest docker image (3.4.3)

**Comment by erwanlr** [comment]
The examples you gave are about the tags, not the users.

However, according to https://developer.wordpress.org/rest-api/reference/users/#list-users, the default per_page for the users is 10.

Instead of adding a pagination, what about a high ```per_page``` argument (such as 300) ?.

Also, worth noting that since WP 4.7.1, the exposure of the usernames is reduced (https://github.com/wpscanteam/wpscan/issues/1038#issuecomment-274416407).

**Comment by erwanlr** [comment]
I couldn't find any reference of the per_page maximum, where did you find it ?

The interesting things to know the number of pages to browse, as well as number of users are given via response headers:

```
x-wp-total: 22
x-wp-totalpages: 3
```

**Comment by erwanlr** [comment]
Implemented in the 3.4.4 branch. Should be released tomorrow and later next week
