### ISSUE TITLE
Vulnerability WPScan Plugin vs. WPScan CLI

### ISSUE THREAD

**Issue by eberhapa** [wpscanteam/wpscan#1306]
Hi,
I just tested the WPScan Plugin and the WPScan cli for the first time so please be patient if I don't understand everything :)

I installed the WPScan Plugin on a local website and also checked the site via the cli.
The WPScan Plugin show a vulnerability for Popup Maker (Fremius Library <= 2.2.3 - Authenticated Option Update - Fixed in version 1.8.3) but the WPScan CLI doesn't. 
I'm using the `-e ap` flag. The plugin also doesn't show up in the identified plugin.

Thanks,
Patrick

**Comment by erwanlr** [comment]
I would definitely trust the plugin output in such case.

w/o knowing which command you ran with the CLI, it's hard to tell as a lot of stuff can produce such results. For example, a security plugin can interfere with the scan, or you forget to use the ```--plugins-detection``` along with the -e option (as its default is detection done passively as written in the Readme)

**Comment by eberhapa** [comment]
Thanks @erwanlr,

I forgot to set --plugins-detection. I sill don't know if I get the same output like the plugin because the scan needs now needs some time to finish. I'll try it on the weekend.

**Comment by erwanlr** [comment]
As you know the plugins installed, you can put them in a file and use ```--plugins-list /path/to-file```, or just test for a few if the file is overkill ```--plugins-list popup-maker,wordpress-seo,etc```. That will save you some time instead of enumerating the 70k+ plugins ^^

**Comment by FireFart** [comment]
The wpscan cli is for doing some blackbox scans against a site where you do not have access to. We try to enumerate as much as possible and show you the data. With the wordpress plugin we take another approach, the white box test. As this runs in your wordpress installation we have full access to the installed plugins and versions.
So if a vulnerability is shown on the plugin, it's there. If the CLI does not show it it's most likely because the plugin could not be enumerated or we did not find a version to check against.

So TL;DR: The CLI gives you the outer sight, the plugin the inner sight.

**Comment by eberhapa** [comment]
Thank you both for your help and explanations.
I tried the --plugins-list flag and it now shows the vulnerability.
