### ISSUE TITLE
When starting scan, an ruby error occour

### ISSUE THREAD

**Issue by kimocoder** [wpscanteam/wpscan#1357]
Running latest git.

warning: Passing whitelist_classes with the 2nd argument of Psych.safe_load is deprecated. Use keyword argument like Psych.safe_load(yaml, whitelist_classes: ...) instead.
warning: Passing whitelist_symbols with the 3rd argument of Psych.safe_load is deprecated. Use keyword argument like Psych.safe_load(yaml, whitelist_symbols: ...) instead.
warning: Passing aliases with the 4th argument of Psych.safe_load is deprecated. Use keyword argument like Psych.safe_load(yaml, aliases: ...) instead.
warning: Passing whitelist_classes with the 2nd argument of Psych.safe_load is deprecated. Use keyword argument like Psych.safe_load(yaml, whitelist_classes: ...) instead.
warning: Passing whitelist_symbols with the 3rd argument of Psych.safe_load is deprecated. Use keyword argument like Psych.safe_load(yaml, whitelist_symbols: ...) instead.
warning: Passing aliases with the 4th argument of Psych.safe_load is deprecated. Use keyword argument like Psych.safe_load(yaml, aliases: ...) instead.
warning: Passing whitelist_classes with the 2nd argument of Psych.safe_load is deprecated. Use keyword argument like Psych.safe_load(yaml, whitelist_classes: ...) instead.
warning: Passing whitelist_symbols with the 3rd argument of Psych.safe_load is deprecated. Use keyword argument like Psych.safe_load(yaml, whitelist_symbols: ...) instead.
warning: Passing aliases with the 4th argument of Psych.safe_load is deprecated. Use keyword argument like Psych.safe_load(yaml, aliases: ...) instead.

**Comment by erwanlr** [comment]
Which version of Ruby and Pysch are you using ?

**Comment by kimocoder** [comment]
Kali default.

Take a look at https://github.com/rubocop-hq/rubocop/issues/6412

**Comment by kimocoder** [comment]
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]

ruby-psych:
  Installed: 3.1.0-1

**Comment by erwanlr** [comment]
I was not able to reproduce the issue in any of my environments. However, I've put a fix in the psych branch (https://github.com/wpscanteam/wpscan/tree/psych). Could you please try it if possible and see if this fixes it ?

**Comment by kimocoder** [comment]
No, still the same deprecation message, it doesn't effect the scan in any way though :+1:

**Comment by erwanlr** [comment]
Using the latest stable Kali Linux, I wasn't able to reproduce the issue w/o screwing up the Kali basically.

I had the issue when manually installing `ruby-psych` via `apt-get` rather than `gem install` which would install the pre-release version, then trying to build WPScan from source. However, the warning won't only be displayed when running WPScan but everything ruby related, such as `gem install` and so on.

Furthermore, the patch I put in the psych branch produced another error, due to the pre-release1 and pre-release2 versions allowing different keys in the #safe_load method.

So I have no idea how you ended up with a pre-release version of Psych, but I would suggest to remove it and switch to a stable one, as the proper fix won't even solve your issue due to the above :/

**Comment by kimocoder** [comment]
Hehe, I do so much weird on my installation, I actually re-install once a week.
I close this down, since it was a deprecation I opened up a issue report just om case. Have a good one :+1:
