### ISSUE TITLE
Version problem

### ISSUE THREAD

**Issue by JK-Love** [wpscanteam/wpscan#1497]
Why? 2.9.2 Version can provide CVE number of current 3.8.1 Version does not provide CVE number
![image](https://user-images.githubusercontent.com/63699609/82136595-1113df80-9842-11ea-8a9b-0a8c27dc8770.png)

![image](https://user-images.githubusercontent.com/63699609/82136596-1bce7480-9842-11ea-93bf-8b85f77e1e67.png)

Or can you tell me how to downgrade

**Comment by JK-Love** [comment]
This problem prevents me from finding the loophole in WordPress in time

**Comment by erwanlr** [comment]
CVE are output as vulnerability's references (when there is one associated to it).

In your second screenshoot, there is no vulnerability output, which can be because:
- There was no vulnerability found
- You did not provide an API Token

<img width="743" alt="Screenshot 2020-05-17 at 09 25 54" src="https://user-images.githubusercontent.com/1668843/82138401-722abb80-9820-11ea-90ba-68af1993e2fa.png">

**Comment by JK-Love** [comment]
Q：There was no vulnerability found
A：Two pictures correspond to the same machine

Q：You did not provide an API Token
A：I don't know what API token is  Can you give me some more tips

**Comment by erwanlr** [comment]
See the Readme, https://github.com/wpscanteam/wpscan#vulnerability-database for the token

**Comment by JK-Love** [comment]
Okay, thank you. I've got it
