### ISSUE TITLE
WPScan is not detecting plugins

### ISSUE THREAD

**Issue by raadsec** [wpscanteam/wpscan#1750]
I am using WPScan to scan a vulnerable WordPress site that contains vulnerable plugin installed. The tool didn't detect any plugins at all

Command that i am using:
`wpscan --url http://site/ --wp-content-dir  wp-content --enumerate ap --clear-cache --wp-plugins-dir wp-content/plugins --stealthy --random-user-agent`

- Wordpress version 6.0.2
- WPScan version 3.8.22
- No firewall is available
- Directory listing is enabled

**Comment by erwanlr** [comment]
The --stealthy option will only perform passive detection, so some plugins might not be detected. You should use `--plugins-detection mixed` instead. Be aware that due to the `--enumerate ap`, all plugins will be checked, which could take some time

Btw, any reason to use the `--wp-content-dir` and `--wp-plugins-dir` options with their default values ?

**Comment by raadsec** [comment]
In general the tool is unable to detect plugins, so i used the mentioned arguments in order to play around and make the tool work, but unfortunately no success

**Comment by alexsanford** [comment]
I ran a test enumerating the most popular plugins on the given site, and I found several. I used the following command.

@raadsec @ocervell could you please confirm whether the command works for you?

`wpscan --random-user-agent --force --plugins-detection mixed -e p --url https://blog.terabox.com`

**Comment by ocervell** [comment]
It's working on the latest update, thanks !

**Comment by alexsanford** [comment]
Good to hear! Feel free to reach out again if you run into further issues 🙂
