### ISSUE TITLE
iframe detection

### ISSUE THREAD

**Issue by pvdl** [wpscanteam/wpscan#756]
Can we check if the HTML code uses ```<iframe>``` and give an informational warning.
You can also check for the hex. value ```3c696672616d650d0a``` which is ```<iframe``` in javascript.
It is a used technique to inject malicious code.
http://resources.infosecinstitute.com/iframe-security-risk/

**Comment by ethicalhack3r** [comment]
We removed malware detection here - https://github.com/wpscanteam/wpscan/commit/2fe675abce87249862bbdaa39f1db44c5dff9808

iframes are used a lot for legitimate purposes like youtube player embeds for example, I think it would produce a too many false positive results to merit the effort

**Comment by secureli** [comment]
Well, since malware identification has been removed... and I still need a
good malware identifier... anyone want to work with me on a malware ID
script? :)

-John

On Thu, Jan 22, 2015 at 2:29 PM, Ryan Dewhurst <notifications@github.com>
wrote:

> Closed #756 <https://github.com/wpscanteam/wpscan/issues/756>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wpscanteam/wpscan/issues/756#event-223245605>.
>



-- 
John M. Martinelli

*digital security & marketing consultant*
http://secureli.com | http://conversionLAUNCH.com

*Office Line: *+1 (317) SECUR - 17 ext. 9
*Direct Line:* +1 (412) 888 - 6090

*This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.*
