### ISSUE TITLE
False positive plugin and theme enumeration

### ISSUE THREAD

**Issue by iCaspar** [wpscanteam/wpscan#767]
Running against mysite.com I am getting false positives for 2 plugins: feed and lazy-seo.
When I enter the location http://mysite.com/wp-content/plugins/feed I get my RSS feed page.
When I enter the location http://mysite.com/wp-content/plugins/lazy-seo I get a mod-secure response from my hosting provider -- which I'm pretty sure means that the directory doesn't exist within an otherwise restricted area, but I could be mistaken.
Same with themes. False positives for caulk and dt-chocolate, and mod-secure page when I go to the locations.
Finally, enumeration fails to find several themes/plugins that *are* installed: twentytwelve, twentythirteen, etc. and wp-show-ids

**Comment by ethicalhack3r** [comment]
Thanks for the report! The feed vulnerability (https://wpvulndb.com/vulnerabilities/6965) has been known to cause false positives. There is currently no official 'feed' plugin on the WordPress repository. I think we might be best removing this vulnerability from our database. More hassle than it is worth.

As for the lazy-seo plugin and dt-chocolate theme, this seems like an environment issue. mod-secure is doing something unusual in this case. If you could provide the full HTTP request and response (URL redacted if you like) we can have a further look into it.

Our theme lists are based on what are on the official WordPress theme databases. I'm not sure if these default themes are on their database. I suspect not and that's why we don't detect them. We should be able to do some research to find out the names of all of these default themes and manually add them to our databases. This might take some time though due to the way we currently generate our lists.

**Comment by iCaspar** [comment]
Here are the headers for the lazy-seo. (I've anonymized the domain name and my current IP, and the cookie. Otherwise it's all as sent/received.)
<pre>
http://mysite.net/wp-content/plugins/lazy-seo/

GET /wp-content/plugins/lazy-seo/ HTTP/1.1
Host: mysite.net
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Cookie: _ga=GA1.2.xxxxxxxxx.xxxxxxxxx; wpSGCacheBypass=1
Connection: keep-alive

HTTP/1.1 302 Found
Server: Apache
Location: /mod_sec.html
Content-Type: text/html; charset=iso-8859-1
Content-Length: 197
Accept-Ranges: bytes
Date: Sat, 07 Feb 2015 12:33:31 GMT
Connection: keep-alive
X-Forwarded-For: xxx.xxx.xxx.xxx
X-Cache: SGCACHE-MISS
----------------------------------------------------------
http://127.0.0.1:49223/test.txt?_=1423312416458

GET /test.txt?_=1423312416458 HTTP/1.1
Host: 127.0.0.1:49223
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0
Accept: text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
X-Requested-With: XMLHttpRequest
Connection: keep-alive

HTTP/1.1 200 OK
Content-Type: text/plain
Date: Sat, 07 Feb 2015 12:33:36 GMT
Last-Modified: Mon, 26 Jan 2015 18:43:29 GMT
----------------------------------------------------------
</pre>

Apparently both themes that are showing false positives for me are premium themes at ThemeForest. Strangely enough, wpscan does find my custom theme -- which I doubt would be in anyone's database since I've not released it into the wild on any site but my own.

**Comment by ethicalhack3r** [comment]
Thanks for the info!

For this specific configuration of mod_security you should be able to add the ```--exclude-content-based 'mod_sec.html'``` option and value to exclude the results which are caught by mod_security.

I think this is the best we can do here as we won't be able to cater for all WAFs and their specific configurations.

Your custom theme would have been detected from the index page's HTML source code, if in use, it will be referenced there.

I have deleted the ```feed``` vulnerability from our database. If you are using the git codebase, you can update your database with the ```--update``` option.

**Comment by erwanlr** [comment]
the ```--exclude-content-based 'mod_sec.html'``` won't do anything there as redirections are followed, it's argument should be a text present in the final 200 response body ^^

**Comment by iCaspar** [comment]
Thanks for clearing this up. Indeed, excluding a string from the 200 response body cleans up the false positives.
