### ISSUE TITLE
Plugin detection false positives

### ISSUE THREAD

**Issue by Veraxus** [wpscanteam/wpscan#903]
On sites where there is a forced login/SSO redirect, WPScan...

- Hangs for a while when finished enumerating plugins & themes, then...
- Incorrectly claims that every plugin in its database is currently installed (1262 as of right now)
- Claims that it can't detect any plugin versions and proceeds to list out every vulnerability for every plugin in its database.
- Does all of the above with themes (lists all themes in db + all vulnerabilities in each).

And to be clear: no, these sites do not have every plugin and theme with known vulnerabilities installed. 😅

**Comment by ethicalhack3r** [comment]
Fix could be what is alluded to in https://github.com/wpscanteam/wpscan/issues/902

To do haomepage and 404 checking against plugins + themes.

**Comment by erwanlr** [comment]
(this has nothing to do with #902)

**Comment by ethicalhack3r** [comment]
Yea, was just coming to that realisation...

**Comment by FireFart** [comment]
@Veraxus could you maybe provide the site in private to team@wpscan.org so we can have a look into this?

**Comment by erwanlr** [comment]
The easiest one to explain:

> Hangs for a while when finished enumerating plugins & themes

This is due to the fact that plugins/themes versions are checked at this moment, so it will try to determine the version of every plugins detected, in this case all the 1262, which take quite a while :x

> Incorrectly claims that every plugin in its database is currently installed (1262 as of right now)

This one is caused by the redirection to the login form when checking the plugins existence. To keep it short, we check 301 & 302 which sometimes are sign of existing plugins. It might produces false positive but we prefer to list them anyway and let the user check for themselves rather than don't output potential stuff (false negative) and miss a vulnerability.

The two other points are related to the one above.

The good news is there is an option to 'filter' and exclude any response matching a pattern during the enumeration process, in your case (with the site you gave us by email), you can use ```--exclude-content-based 'Please use your'```
