### ISSUE TITLE
wp_versions.xml: checksums do not match

### ISSUE THREAD

**Issue by NemoOzil** [wpscanteam/wpscan#931]
root@kali:~/wpscan# ruby wpscan.rb --update
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...

**[!] wp_versions.xml: checksums do not match**

**Comment by ethicalhack3r** [comment]
Thanks for the report!

Seems to be working for me. Can you try again maybe? And if it doesn't work can you try with the debug flag?

```./wpscan.rb --update --debug```

**Comment by tititototutu** [comment]
Hi,

I have the same issue. here are the logs

./wpscan.rb --update --verbose
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[+] Checking local_vulnerable_files.xml
  [i] Already Up-To-Date
[+] Checking local_vulnerable_files.xsd
  [i] Already Up-To-Date
[+] Checking timthumbs.txt
  [i] Already Up-To-Date
[+] Checking user-agents.txt
  [i] Already Up-To-Date
[+] Checking wp_versions.xml
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: 2f07f91dd7f3aff113868c13d9ce87b04286c95bf7e489c8c884a084c1753c8cdef434f334df65a9573480b6bd911de1ba417a8140b4444f01c013065996070d
  [i] Database File Checksum  : a8e626561143e9498fb3a404eb16a7e2b524eefe05708a626f158a308a809abd186044d5e8573eb705dd6bb24476b8061d8401e6a3fe04833f24f27a463afd54
  [i] Restoring Backup due to error
  [i] Deleting Backup

[!] wp_versions.xml: checksums do not match
[!] Trace:
[!] /opt/wpscan/lib/common/db_updater.rb:104:in `block in update'
/opt/wpscan/lib/common/db_updater.rb:84:in `each'
/opt/wpscan/lib/common/db_updater.rb:84:in `update'
./wpscan.rb:73:in `main'
./wpscan.rb:470:in `<main>'

**Comment by ethicalhack3r** [comment]
I think the issue might have been that the checksum was not updated on Amazon S3, can you try now please?

**Comment by FireFart** [comment]
I think this might be caused by amazon not having invalidated all caches at this time. I added more verbose output to also print the non matching hashes https://github.com/wpscanteam/wpscan/commit/75b8c303e22ad86704a23b464f3b8ba03a9079e1

**Comment by tititototutu** [comment]
Thanks for the quick reply.

always the same issue 

13:45:47 root@srv: /opt/wpscan # git pull
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
Dépaquetage des objets: 100% (5/5), fait.
Depuis https://github.com/wpscanteam/wpscan
   bd7a493..75b8c30  master     -> origin/master
Mise à jour bd7a493..75b8c30
Fast-forward
 lib/common/db_updater.rb | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
15:21:32 root@srv: /opt/wpscan # ./wpscan.rb --update --verbose
_______________________________________________________________
        __          _______   _____                  
        \ \        / /  __ \ / ____|                 
         \ \  /\  / /| |__) | (___   ___  __ _ _ __  
          \ \/  \/ / |  ___/ \___ \ / __|/ _` | '_ \ 
           \  /\  /  | |     ____) | (__| (_| | | | |
            \/  \/   |_|    |_____/ \___|\__,_|_| |_|

        WordPress Security Scanner by the WPScan Team 
                       Version 2.9
          Sponsored by Sucuri - https://sucuri.net
   @_WPScan_, @ethicalhack3r, @erwan_lr, pvdl, @_FireFart_
_______________________________________________________________

[i] Updating the Database ...
[+] Checking local_vulnerable_files.xml
  [i] Already Up-To-Date
[+] Checking local_vulnerable_files.xsd
  [i] Already Up-To-Date
[+] Checking timthumbs.txt
  [i] Already Up-To-Date
[+] Checking user-agents.txt
  [i] Already Up-To-Date
[+] Checking wp_versions.xml
  [i] Needs to be updated
  [i] Backup Created
  [i] Downloading new file
  [i] Downloaded File Checksum: 2f07f91dd7f3aff113868c13d9ce87b04286c95bf7e489c8c884a084c1753c8cdef434f334df65a9573480b6bd911de1ba417a8140b4444f01c013065996070d
  [i] Database File Checksum  : a8e626561143e9498fb3a404eb16a7e2b524eefe05708a626f158a308a809abd186044d5e8573eb705dd6bb24476b8061d8401e6a3fe04833f24f27a463afd54
  [i] Restoring Backup due to error
  [i] Deleting Backup

[!] wp_versions.xml: checksums do not match (local: 2f07f91dd7f3aff113868c13d9ce87b04286c95bf7e489c8c884a084c1753c8cdef434f334df65a9573480b6bd911de1ba417a8140b4444f01c013065996070d remote: a8e626561143e9498fb3a404eb16a7e2b524eefe05708a626f158a308a809abd186044d5e8573eb705dd6bb24476b8061d8401e6a3fe04833f24f27a463afd54)
[!] Trace:
[!] /opt/wpscan/lib/common/db_updater.rb:104:in `block in update'
/opt/wpscan/lib/common/db_updater.rb:84:in `each'
/opt/wpscan/lib/common/db_updater.rb:84:in `update'
./wpscan.rb:73:in `main'
./wpscan.rb:470:in `<main>'

**Comment by FireFart** [comment]
jeah looks like the sha512 file is not updated on amazon....currently investigating

**Comment by tititototutu** [comment]
i delete the wp_versions.xml reference in /opt/wpscan/lib/common/db_updater.rb and it did the trick... ;)

**Comment by FireFart** [comment]
@tititototutu it should be fixed now. The sha512 files were uploaded, but not invalidated so you were getting the cached version. Your change btw prevents you from getting the latest wp_versions file with the 4.5.1 hashes.

**Comment by tititototutu** [comment]
everything is fine now. thanks!
