### ISSUE TITLE
Updating the database.

### ISSUE THREAD

**Issue by lnxg33k** [wpscanteam/wpscan#992]
I recommend the DB to be hosted on GitHub instead of data.wpscan.org which is behind CloudFlare.
because, as an example, when you run the update while using TOR as a socks proxy it will fail with a status: 403.

**Comment by FireFart** [comment]
@lnxg33k Jeah we know about the TOR problem.
As we are an open source project run by a few people cost is always a big factor. CLoudflares CDN is free and provides some good statistics. We had the data files published to Github in the past but this was not working flawlessy. The API is a P I T A and is very error prone. Also there are no statistics on the files like number of downloads or traffic generated.
That's why we are currently using cloudflare but it may change in the future because we also have experienced some caching problems with some users.
